language: objective-c
xcode_project: CSyncSDK.xcodeproj # path to your xcodeproj folder
xcode_scheme: CSyncSDK-iOS
osx_image: xcode8.2
before_script: 
  - brew update
  - brew install carthage
  - carthage update