language: objective-c
xcode_project: CSyncSDK.xcodeproj # path to your xcodeproj folder
xcode_scheme: CSyncSDK-iOS
osx_image: xcode8.3
before_script: 
  - carthage update
  - /usr/libexec/PlistBuddy -c "Set CSYNC_HOST $CSYNC_HOST" Tests/CSyncSDKTests/Config.plist
  - /usr/libexec/PlistBuddy -c "Set CSYNC_PORT $CSYNC_PORT" Tests/CSyncSDKTests/Config.plist
  - /usr/libexec/PlistBuddy -c "Set CSYNC_DEMO_PROVIDER $CSYNC_DEMO_PROVIDER" Tests/CSyncSDKTests/Config.plist
  - /usr/libexec/PlistBuddy -c "Set CSYNC_DEMO_TOKEN $CSYNC_DEMO_TOKEN" Tests/CSyncSDKTests/Config.plist
script: 
  - xcodebuild -project CSyncSDK.xcodeproj -scheme CSyncSDK-iOS -destination platform='iOS Simulator',name='iPhone 6',OS='10.3' clean test
  - xcodebuild -project CSyncSDK.xcodeproj -scheme CSyncSDK-iOS -destination platform='iOS Simulator',name='iPhone 6',OS='9.3' clean test
  - xcodebuild -project CSyncSDK.xcodeproj -scheme CSyncSDK-OSX -destination platform='macOS' clean test
  - swift -version
  - swift build -Xlinker -lsqlite3 -Xlinker -lz
  - swift test -Xlinker -lsqlite3 -Xlinker -lz
  - pod spec lint --allow-warnings
branches:
  only:
  - master
